### ISSUE TITLE
unrelated matches having a result

### ISSUE THREAD

**Issue by seldaerkilic** [davetyson/project4#26]
Nice and clean landing page, and really nice design. Well done!
The one thing I noticed is I have a comparison result for unrelated matches. Not sure if it's possible to match the actual book and the films with the data set, but it might be worthy to think about an error handling.

![image](https://user-images.githubusercontent.com/120135545/231205451-e0e9bc4e-2d35-4a0f-a257-0ba494956f74.png)

**Comment by davetyson** [comment]
Yeah this is a great idea! We thought about how you would have that option to compare different books but discussed different approaches. We will see what we can do to improve this!
