### ISSUE TITLE
Minor console errors when submitting input

### ISSUE THREAD

**Issue by paigethai** [davetyson/project4#27]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/84000119/231205977-6298b327-bdde-44c4-8e7d-29f030a1854b.png">

I'd definitely review these to see if there's anything y'all can do to prevent these errors from happening when the user submits.

**Comment by davetyson** [comment]
Yeah I saw these too! But wasn't sure what they were, definitely gonna look into it!
