### ISSUE TITLE
[Moderate] h5/h3 element used for description

### ISSUE THREAD

**Issue by chelseycornejo** [davetyson/project4#28]
<img width="1424" alt="Screenshot 2023-04-11 at 11 01 31 AM" src="https://user-images.githubusercontent.com/122055774/231205878-086ed6ec-e908-48eb-a888-c28f2b7da25d.png">

<img width="1365" alt="Screenshot 2023-04-11 at 11 06 48 AM" src="https://user-images.githubusercontent.com/122055774/231206565-94ce01e2-4246-4542-ac80-1c2ff139fb10.png">

Maybe utilize a p tag instead of the h5/h3 for the descriptions as they are not headers

**Comment by davetyson** [comment]
Ooooh yeah these should definitely be a p! Thanks!
