### ISSUE TITLE
[Small] Including a cursor: pointer on clickable items

### ISSUE THREAD

**Issue by chelseycornejo** [davetyson/project4#32]
<img width="204" alt="Screenshot 2023-04-11 at 11 01 58 AM" src="https://user-images.githubusercontent.com/122055774/231207376-b379e839-a2b7-4605-84d5-5ff7726800d4.png">

Adding it to the search button and the book/movies so the user knows they are clickable items

**Comment by stevesidoli** [comment]
This is complete!
