### ISSUE TITLE
Reducing padding and margin to have borders flushed

### ISSUE THREAD

**Issue by paigethai** [davetyson/project4#33]
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/84000119/231207596-b057cd25-ab77-4d25-846b-6cffb32b874d.png">
- This looks great!

vs.

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/84000119/231207027-96ad2c7f-aee8-4324-a120-d2749bc60ef7.png">

- When only one side is populated, there's additional margin/padding making it pop out a bit more - wondering if there's anything minor y'all can do to make it stylistically more cohesive

**Comment by davetyson** [comment]
Whoooa this is awesome! Never noticed this haha, we're gonna look into this definitely!
