### ISSUE TITLE
Use display:none over visibility:hidden

### ISSUE THREAD

**Issue by DevinD55** [davetyson/project4#34]
![Screen Shot 2023-04-11 at 11 16 03 AM](https://user-images.githubusercontent.com/121203031/231208986-76d6c243-56ec-4ad7-8c46-078252171354.png)

I'm 90% sure visibility hidden will still be read by a screen reader. display:none and display: block might work better.

Edit: this is for the results container

**Comment by stevesidoli** [comment]
Change has been made!
