### ISSUE TITLE
User navigation isn't as intuitive once results are generated

### ISSUE THREAD

**Issue by paigethai** [davetyson/project4#35]
The pop-up for the result is immediately generated after the user submits. But it is not intuitive for the user to know that there is more information on the results behind the pop-out. Maybe consider having more directions for the user to follow -- giving them the option to inspect the results of the book or movie. 

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/84000119/231209495-863932b2-f9b1-4f35-8fd5-94908e2b2fc9.png">

or maybe you can add it to the landing page :) 
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/84000119/231210250-63f2a48f-20ee-4766-a759-9e3ad1df68ba.png">

**Comment by davetyson** [comment]
These are two amazing placement suggestions! Good catch, thank you Paige 🥳
