### ISSUE TITLE
adding in very random text causes strange search result 

### ISSUE THREAD

**Issue by kenziebburke** [davetyson/project4#36]
I placed the following text into the input field "
  
    #source {
      color: red;
    }
    #text {
      text-transform: uppercase;
    }
 
  HIDDEN TEXT" just to really try to mess with the program, though the there was proper error handling when there was not movie result... there were a few very random books that appeared that looked like they had nothing to do with the input.... getting really nitpicky bcc i really am struggling to find any issues!

**Comment by davetyson** [comment]
Haha it's crazy how forgiving the Google Books API is, it will almost always find _something_. Thanks for taking a look, we'll see what kind of error handling we can do here!
