### ISSUE TITLE
FeedBack

### ISSUE THREAD

**Issue by RobertoJan** [davetyson/project4#41]
Good Job! code looks super clean!  Error handling is really good too! Components make sense and while I didn't get to understand all the code it looked everything was set up in conditionals and state to cover all the logic  behind the app comparison and retrieving the data from the API, the useEffect on the Footer was also neat! Additionally I tested on Ipad2 and Android Phone, the app had no notable issues from my testing

**Comment by davetyson** [comment]
Thank you Roberto! Appreciate your feedback!
